### ISSUE TITLE
Rename block ip and unblock ip parameter: "destination_network" to "ip"

### ISSUE THREAD

**Issue by codejulen** [taruch/phantom_cisco_firepower#1]
Currently in the actions block ip and unblock ip, the main parameter is given the name "destination_network".

By renaming the field to "ip," the action follows the convention of other apps that can block and unblock IPs.

This is especially important for Playbooks.  With this change, a user is able to configure a playbook to use Block IP on all of its assets (PAN, FirePower, etc.) without extra configuration of the input parameters.

**Comment by taruch** [comment]
Resolved in commit 337d305f5ff5af1ebc650678e50e796ad6d9cef0.
