### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by codejulen** [taruch/phantom_cisco_firepower#2]
In the function "validate_ip", the following compilation errors appear:
` ./cisco_firepower_connector.py:285: error (E1101, no-member, FP_Connector.validate_ip) Instance of 'str' has no 'prefixlen' member`

` ./cisco_firepower_connector.py:285: error (E1101, no-member, FP_Connector.validate_ip) Instance of 'str' has no 'network' member`

` ./cisco_firepower_connector.py:285: error (E1101, no-member, FP_Connector.validate_ip) Instance of 'str' has no 'ip' member`

` ./cisco_firepower_connector.py:286: error (E1101, no-member, FP_Connector.validate_ip) Instance of 'str' has no 'network' member`

` ./cisco_firepower_connector.py:287: error (E1101, no-member, FP_Connector.validate_ip) Instance of 'str' has no 'prefixlen' member`

This is due to line #280:
`ip_net = ''`

The reassignment of ip_net within the try block is correct, but the compiler assumes that the reassignment is never done, which can conflict with the if block at the end of the function.  It might be better to move the if block and the return True within the try block.

In the function "_deploy_config", the following compilation error appears:
` ./cisco_firepower_connector.py:337: error (E1101, no-member, FP_Connector._deploy_config) Instance of 'LookupDict' has no 'ok' member`

I haven't gotten to the root of this problem, but since requests.codes.ok only returns '200', it might be better to just do:
`if api_response.status_code == 200:`

**Comment by taruch** [comment]
What are you doing to get a compile error?  I'm not getting any.

**Comment by codejulen** [comment]
Internal compilation script - after further inspection it's a Pylint error, which is not as big of a problem as I had assumed.  You can choose to close this if you'd like
